// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: grpc/auction.proto

package auction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EAck int32

const (
	EAck_Fail      EAck = 0
	EAck_Success   EAck = 1
	EAck_Exception EAck = 2
)

// Enum value maps for EAck.
var (
	EAck_name = map[int32]string{
		0: "Fail",
		1: "Success",
		2: "Exception",
	}
	EAck_value = map[string]int32{
		"Fail":      0,
		"Success":   1,
		"Exception": 2,
	}
)

func (x EAck) Enum() *EAck {
	p := new(EAck)
	*p = x
	return p
}

func (x EAck) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EAck) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_auction_proto_enumTypes[0].Descriptor()
}

func (EAck) Type() protoreflect.EnumType {
	return &file_grpc_auction_proto_enumTypes[0]
}

func (x EAck) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EAck.Descriptor instead.
func (EAck) EnumDescriptor() ([]byte, []int) {
	return file_grpc_auction_proto_rawDescGZIP(), []int{0}
}

type BidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      *int64                 `protobuf:"varint,1,opt,name=senderId" json:"senderId,omitempty"`
	Timestamp     *uint64                `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Amount        *uint64                `protobuf:"varint,3,opt,name=amount" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidRequest) Reset() {
	*x = BidRequest{}
	mi := &file_grpc_auction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest) ProtoMessage() {}

func (x *BidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest.ProtoReflect.Descriptor instead.
func (*BidRequest) Descriptor() ([]byte, []int) {
	return file_grpc_auction_proto_rawDescGZIP(), []int{0}
}

func (x *BidRequest) GetSenderId() int64 {
	if x != nil && x.SenderId != nil {
		return *x.SenderId
	}
	return 0
}

func (x *BidRequest) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *BidRequest) GetAmount() uint64 {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return 0
}

type BidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      *int64                 `protobuf:"varint,1,opt,name=senderId" json:"senderId,omitempty"`
	Timestamp     *uint64                `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Ack           *EAck                  `protobuf:"varint,3,opt,name=ack,enum=EAck" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidResponse) Reset() {
	*x = BidResponse{}
	mi := &file_grpc_auction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidResponse) ProtoMessage() {}

func (x *BidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidResponse.ProtoReflect.Descriptor instead.
func (*BidResponse) Descriptor() ([]byte, []int) {
	return file_grpc_auction_proto_rawDescGZIP(), []int{1}
}

func (x *BidResponse) GetSenderId() int64 {
	if x != nil && x.SenderId != nil {
		return *x.SenderId
	}
	return 0
}

func (x *BidResponse) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *BidResponse) GetAck() EAck {
	if x != nil && x.Ack != nil {
		return *x.Ack
	}
	return EAck_Fail
}

type Outcome struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SenderId           *int64                 `protobuf:"varint,1,opt,name=senderId" json:"senderId,omitempty"`
	Timestamp          *uint64                `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	IsAuctionCompleted *bool                  `protobuf:"varint,3,opt,name=isAuctionCompleted" json:"isAuctionCompleted,omitempty"`
	LeadingBid         *uint64                `protobuf:"varint,4,opt,name=leadingBid" json:"leadingBid,omitempty"`
	LeadingID          *int64                 `protobuf:"varint,5,opt,name=leadingID" json:"leadingID,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Outcome) Reset() {
	*x = Outcome{}
	mi := &file_grpc_auction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outcome) ProtoMessage() {}

func (x *Outcome) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outcome.ProtoReflect.Descriptor instead.
func (*Outcome) Descriptor() ([]byte, []int) {
	return file_grpc_auction_proto_rawDescGZIP(), []int{2}
}

func (x *Outcome) GetSenderId() int64 {
	if x != nil && x.SenderId != nil {
		return *x.SenderId
	}
	return 0
}

func (x *Outcome) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *Outcome) GetIsAuctionCompleted() bool {
	if x != nil && x.IsAuctionCompleted != nil {
		return *x.IsAuctionCompleted
	}
	return false
}

func (x *Outcome) GetLeadingBid() uint64 {
	if x != nil && x.LeadingBid != nil {
		return *x.LeadingBid
	}
	return 0
}

func (x *Outcome) GetLeadingID() int64 {
	if x != nil && x.LeadingID != nil {
		return *x.LeadingID
	}
	return 0
}

type Void struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      *int64                 `protobuf:"varint,1,opt,name=senderId" json:"senderId,omitempty"`
	Timestamp     *uint64                `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Void) Reset() {
	*x = Void{}
	mi := &file_grpc_auction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_grpc_auction_proto_rawDescGZIP(), []int{3}
}

func (x *Void) GetSenderId() int64 {
	if x != nil && x.SenderId != nil {
		return *x.SenderId
	}
	return 0
}

func (x *Void) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

var File_grpc_auction_proto protoreflect.FileDescriptor

const file_grpc_auction_proto_rawDesc = "" +
	"\n" +
	"\x12grpc/auction.proto\"^\n" +
	"\n" +
	"BidRequest\x12\x1a\n" +
	"\bsenderId\x18\x01 \x01(\x03R\bsenderId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\"`\n" +
	"\vBidResponse\x12\x1a\n" +
	"\bsenderId\x18\x01 \x01(\x03R\bsenderId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12\x17\n" +
	"\x03ack\x18\x03 \x01(\x0e2\x05.eAckR\x03ack\"\xb1\x01\n" +
	"\aOutcome\x12\x1a\n" +
	"\bsenderId\x18\x01 \x01(\x03R\bsenderId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12.\n" +
	"\x12isAuctionCompleted\x18\x03 \x01(\bR\x12isAuctionCompleted\x12\x1e\n" +
	"\n" +
	"leadingBid\x18\x04 \x01(\x04R\n" +
	"leadingBid\x12\x1c\n" +
	"\tleadingID\x18\x05 \x01(\x03R\tleadingID\"@\n" +
	"\x04void\x12\x1a\n" +
	"\bsenderId\x18\x01 \x01(\x03R\bsenderId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp*,\n" +
	"\x04eAck\x12\b\n" +
	"\x04Fail\x10\x00\x12\v\n" +
	"\aSuccess\x10\x01\x12\r\n" +
	"\tException\x10\x022_\n" +
	"\x04Node\x12\"\n" +
	"\x03Bid\x12\v.BidRequest\x1a\f.BidResponse\"\x00\x12\x1b\n" +
	"\x06Result\x12\x05.void\x1a\b.Outcome\"\x00\x12\x16\n" +
	"\x04Ping\x12\x05.void\x1a\x05.void\"\x00B\vZ\t./auctionb\beditionsp\xe8\a"

var (
	file_grpc_auction_proto_rawDescOnce sync.Once
	file_grpc_auction_proto_rawDescData []byte
)

func file_grpc_auction_proto_rawDescGZIP() []byte {
	file_grpc_auction_proto_rawDescOnce.Do(func() {
		file_grpc_auction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_auction_proto_rawDesc), len(file_grpc_auction_proto_rawDesc)))
	})
	return file_grpc_auction_proto_rawDescData
}

var file_grpc_auction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_auction_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpc_auction_proto_goTypes = []any{
	(EAck)(0),           // 0: eAck
	(*BidRequest)(nil),  // 1: BidRequest
	(*BidResponse)(nil), // 2: BidResponse
	(*Outcome)(nil),     // 3: Outcome
	(*Void)(nil),        // 4: void
}
var file_grpc_auction_proto_depIdxs = []int32{
	0, // 0: BidResponse.ack:type_name -> eAck
	1, // 1: Node.Bid:input_type -> BidRequest
	4, // 2: Node.Result:input_type -> void
	4, // 3: Node.Ping:input_type -> void
	2, // 4: Node.Bid:output_type -> BidResponse
	3, // 5: Node.Result:output_type -> Outcome
	4, // 6: Node.Ping:output_type -> void
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_auction_proto_init() }
func file_grpc_auction_proto_init() {
	if File_grpc_auction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_auction_proto_rawDesc), len(file_grpc_auction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_auction_proto_goTypes,
		DependencyIndexes: file_grpc_auction_proto_depIdxs,
		EnumInfos:         file_grpc_auction_proto_enumTypes,
		MessageInfos:      file_grpc_auction_proto_msgTypes,
	}.Build()
	File_grpc_auction_proto = out.File
	file_grpc_auction_proto_goTypes = nil
	file_grpc_auction_proto_depIdxs = nil
}
